### ISSUE TITLE
Please help, I did all and it worked, but somehow suddenly It stoped asking for permission on the device

### ISSUE THREAD

**Issue by santosadrian** [vanderblugen/Yubico-Passwordless-Login-with-Linux#1]
Is there any form to make it imposible to disable? Please help.

**Comment by vanderblugen** [comment]
I haven't run into this issue.  Is it asking for a user/password?  Cause that would most likely be an issue with the files in the `/etc/pam.d` directory.  The script goes thru and adds `@include common-u2f` before `@include common-auth` in several files.   If the `@include common-u2f` is after the `@include common-auth` line it will ask for the user/password first.  Does this help?

**Comment by santosadrian** [comment]
I followed the steps again and now It's working, but I think somebody disables it (I have a firmware rootkit I can't get rid of)
![TnzYcYS](https://user-images.githubusercontent.com/8394201/86131582-1ec9af80-bae6-11ea-9957-373d3e2d5b85.png)
I'll reread your suggestions when I have a cleared mind, need to spleep. BTW, I disabled root account and debian won't boot anymore, I think it's related to the rootkit, same as doing a memdump and crash whole system and It was no recoverable.
Thank you for your fast response.

**Comment by vanderblugen** [comment]
It looks like you are getting a command confused.  Are you just trying to run a super user command?  

In order to run `su` directly you need the root account enabled.

`sudo su` would pull you into a root prompt requiring the `Please touch the device.`

You can do `su user`

If you want that without a password you need to modify the /etc/pam.d/su file.
Add `@include common-u2f` to a new line right before `@include common-auth`

If you want a script to do it

```
sudo su
cd /etc/pam.d
echo 'auth sufficient pam_u2f.so authfile=/etc/u2f_mappings cue' > common-u2f
for f in su; do
mv $f $f~
awk '/@include common-auth/ {print "@include common-u2f"}; {print}' $f~ > $f
done
exit

```

**Comment by santosadrian** [comment]
Excuse my crappy english. I miss something in translation.
I did replace xscreensaver wich I don't use for su "for f in gdm-password lightdm sudo login polkit-1 su; do", now works fine, I have to touch the device when I do sudo or su command. Wich is great, I have a firmware rootkit and I don't think this can stop it, but anyhow the cpu ussage is lower, like the net, memory and so on. So I think it might mitigate the rootkit a little bit.
Thank you for your patience and support.

EDIT: If you know any howto for hardening even more my PC with u2f please let me know.

**Comment by vanderblugen** [comment]
If your looking for hardening further if you remove the `@include common-auth` from the files referenced it won't ever ask for a password and just ask for the u2f.  I haven't tested that thou.

**Comment by santosadrian** [comment]
> If your looking for hardening further if you remove the `@include common-auth` from the files referenced it won't ever ask for a password and just ask for the u2f. I haven't tested that thou.

I did notice that when the device is not connected and in fido app (I use a ledger nano s, very good little hardware wallet) debian asks for the password, I'll do what you suggest, only thing I have to do is follow the steps but removing **@include common-auth** from it right?

Thank you very much. This helps a lot and gives a calm mind when you were heavily attacked a few weeks ago.

I tried this, when de device is not connected it keeps asking for password. What did I wrong? (I didn't reboot)
**sudo su
cd /etc/pam.d
echo 'auth sufficient pam_u2f.so authfile=/etc/u2f_mappings cue' > common-u2f
for f in gdm-password lightdm sudo login polkit-1 xscreensaver su; do
mv $f $f~
awk '{print "@include common-u2f"}; {print}' $f~ > $f
done
exit**

![KeepsAskingForPassword](https://user-images.githubusercontent.com/8394201/86495865-4dac8380-bd7b-11ea-8bec-2f3711892533.png)

**Comment by vanderblugen** [comment]
Oh crap.  I must have missed the email on this.  Did you get it working?

**Comment by santosadrian** [comment]
Yeah thank you anyway. I edited manually the files under /etc/pam.d and removed common-auth, now if the device is not connected or something gives an error.

**Comment by vanderblugen** [comment]
If you are looking to put it back the files that are changed.  This is provided that they are still there.
In the `/etc/pam.d` folder, the altered files are backed up with a ~ on the end of the name.  
Hope that helps.

**Comment by vanderblugen** [comment]
Ok.  It does sound like you have it working like you wanted to.  If you are looking to put it back the files that are changed. This is provided that they are still there.  
In the `/etc/pam.d` folder, the altered files are backed up with a ~ on the end of the name.

**Comment by santosadrian** [comment]
Yeah, more or less, just one question, running this: 
`cd /etc/pam.d`
`echo 'auth sufficient pam_u2f.so authfile=/etc/u2f_mappings cue' > common-u2f`
`for f in gdm-password lightdm sudo login polkit-1 su; do`
`mv $f $f~`
`awk '{print "@include common-u2f"}; {print}' $f~ > $f`
`done`
`exit`
I get this in the files:
![2020-10-27_11-13](https://user-images.githubusercontent.com/8394201/97294136-8221df00-1845-11eb-937e-70906bf01bcb.png)
[https://i.imgur.com/tePy6Rh.png](url)
Do you get the same spam? Why not just simply `echo "@include common-u2f" >> $f`

And just one suggestion, in:
`echo Press the button`
`sudo pamu2fcfg -u root > /etc/u2f_mappings`
`sudo pamu2fcfg -u "$USER" >> /etc/u2f_mappings`

You can insert this so you don't have to edit manually /etc/u2f_mappings:
`echo Press the button... [mapping root keys]`
`sudo pamu2fcfg -u root > /etc/u2f_mappings`
**`sudo echo -ne "\r" >> /etc/u2f_mappings`**
`echo Press again the button... [mapping "$USER" keys]`
`sudo pamu2fcfg -u "$USER" >> /etc/u2f_mappings`
`echo Done.`

Cheers.

**Comment by vanderblugen** [comment]
@santosadrian, yea that script messed up somewhere.  It looks like it was entered every other line in the file.  Remove the spammy parts.  If you need the original files, the script makes a copy of the original with a ~ at the end of the file.  

And the reason why `echo "@include common-u2f" >> $f` doesn't work by itself is because that would add it onto the end of the file.
