### ISSUE TITLE
polkit-1 policy does not work anymore in Ubuntu version 24.04

### ISSUE THREAD

**Issue by jovial-snyder** [vanderblugen/Yubico-Passwordless-Login-with-Linux#5]
Executing `update-mapping.sh` with `polkit-1` in the `SERVICES` list will return with a `[SKIP]`. I think they moved the polkit directory to a different location.

**Comment by vanderblugen** [comment]
I just installed a fresh version of 24.04 and ran it without issue.  Could you provide more context on the error that you received.

**Comment by jovial-snyder** [comment]
This is on a new Ubuntu 24.04 installation:

```
~/Dev/Yubico-Passwordless-Login-with-Linux (master ✗) sudo ./update-mapping.sh
[SKIP] polkit-1 does not exist
```

**Comment by jovial-snyder** [comment]
I changed the title and my last comment because I have this problem already on 24.04. This is a new installation (not upgraded). I can test it again today on a newly created VM, just to be sure.

**Comment by jovial-snyder** [comment]
From a Ubuntu VM I created just now:

```
user@USER-VM-UBUNTU:~/Downloads/Yubico-Passwordless-Login-with-Linux$ sudo ./update-mapping.sh 
[SKIP] polkit-1 does not exist
user@USER-VM-UBUNTU:~/Downloads/Yubico-Passwordless-Login-with-Linux$ hostnamectl 
 Static hostname: USER-VM-UBUNTU
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: ec3057271e1449b4a2033ec2e66633b6
         Boot ID: bb5ccd51e4be4dedaf42894338fc5a95
  Virtualization: oracle
Operating System: Ubuntu 24.04.1 LTS              
          Kernel: Linux 6.8.0-49-generic
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox
Firmware Version: VirtualBox
   Firmware Date: Fri 2006-12-01
    Firmware Age: 17y 11month 4w
```

**Comment by vanderblugen** [comment]
I don't have time to have a good look at it right now.  I'm sure it moved to another directory, if you want to address the script that's fine.  Send it over and I'll test it and merge it in if it works.

**Comment by jovial-snyder** [comment]
I will push a fix in the coming days. All that is needed to make polkit-1 work for new Ubuntu versions (>= 24.04) is to check if the file exists in `/etc/pam.d/`. If it doesn't exist, copy it over from `/usr/lib/pam.d/polkit-1` before running the script. That's it. Now it works again.

**Comment by vanderblugen** [comment]
Update merged in.  Closing.
